###################
# UseOpenCV.cmake #
###################

FIND_PACKAGE(OpenCV REQUIRED HINTS "$ENV{SMGLIB_OPENCV_DIR}" "$ENV{HOMEDRIVE}$ENV{HOMEPATH}/Downloads/opencv-3.4.15/build")
INCLUDE_DIRECTORIES(BEFORE SYSTEM ${OpenCV_INCLUDE_DIRS})
ADD_DEFINITIONS(-DWITH_OPENCV)
